#!/usr/bin/python
import csv

XT_KBD = 8
JAVA = 14
template = """
package com.tightvnc.vncviewer;
import java.awt.event.KeyEvent;
// Don't edit. Auto generated by keymap-gen.py
public class KeyboardEventMap {
    // Map from Java key code to Rfb key code 
    public static final int[] java2rfb = new int[0x10000];
    static{	
%s
    }
}"""

reader = csv.reader(open('keymaps.csv', 'rb'), delimiter=",")
lines = []

for row in reader:
    if reader.line_num == 1:
        continue
    j = row[JAVA]
    x = row[XT_KBD] and int(row[XT_KBD])

    if j and x:
        # RFB keycodes are XT kbd keycodes with a slightly
        # different encoding of 0xe0 scan codes. RFB uses
        # the high bit of the first byte, instead of the low
        # bit of the second byte.
        rfb = ((x & 0x100) >> 1) | (x & 0x7f)
        lines.append("java2rfb[KeyEvent.%s] = %s;" % (j, rfb))

file = open("KeyboardEventMap.java", "wb")

file.write(template % ("\n".join(lines)))
file.close()
